// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/brands" | "/admin/categories" | "/admin/customers" | "/admin/dashboard" | "/admin/emails" | "/admin/finance" | "/admin/inventory" | "/admin/marketing" | "/admin/orders" | "/admin/orders/[orderId]" | "/admin/orders/new" | "/admin/payments" | "/admin/products" | "/admin/roles" | "/admin/settings" | "/admin/shipping" | "/admin/users" | "/auth/forgot-password" | "/auth/login" | "/auth/profile" | "/auth/register" | "/auth/reset-password" | "/auth/verify-email" | "/cart" | "/checkout" | "/licenses" | "/orders" | "/orders/[orderId]" | "/orders/[orderId]/confirmation" | "/orders/[orderId]/payment" | "/privacy" | "/products" | "/products/[slug]" | "/settings" | "/shop/brands" | "/shop/brands/[slug]" | "/shop/categories" | "/shop/categories/[slug]" | "/terms" | "/track-order"
type AppRouteHandlerRoutes = "/api/[...path]" | "/api/admin/emails/[emailId]/retry" | "/api/admin/orders" | "/api/admin/orders/[orderId]/email-invoice" | "/api/admin/payments/collect" | "/api/admin/reconcile" | "/api/checkout" | "/api/internal/email-outbox" | "/api/payments/mpesa/callback" | "/api/payments/mpesa/initiate" | "/api/payments/status/[paymentId]" | "/auth/callback" | "/auth/oauth/google" | "/product-feed.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/products" | "/shop/brands" | "/shop/brands/[slug]" | "/shop/categories" | "/shop/categories/[slug]"
type RedirectRoutes = "/shop/categories/connectivity"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/brands": {}
  "/admin/categories": {}
  "/admin/customers": {}
  "/admin/dashboard": {}
  "/admin/emails": {}
  "/admin/finance": {}
  "/admin/inventory": {}
  "/admin/marketing": {}
  "/admin/orders": {}
  "/admin/orders/[orderId]": { "orderId": string; }
  "/admin/orders/new": {}
  "/admin/payments": {}
  "/admin/products": {}
  "/admin/roles": {}
  "/admin/settings": {}
  "/admin/shipping": {}
  "/admin/users": {}
  "/api/[...path]": { "path": string[]; }
  "/api/admin/emails/[emailId]/retry": { "emailId": string; }
  "/api/admin/orders": {}
  "/api/admin/orders/[orderId]/email-invoice": { "orderId": string; }
  "/api/admin/payments/collect": {}
  "/api/admin/reconcile": {}
  "/api/checkout": {}
  "/api/internal/email-outbox": {}
  "/api/payments/mpesa/callback": {}
  "/api/payments/mpesa/initiate": {}
  "/api/payments/status/[paymentId]": { "paymentId": string; }
  "/auth/callback": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/oauth/google": {}
  "/auth/profile": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/auth/verify-email": {}
  "/cart": {}
  "/checkout": {}
  "/licenses": {}
  "/orders": {}
  "/orders/[orderId]": { "orderId": string; }
  "/orders/[orderId]/confirmation": { "orderId": string; }
  "/orders/[orderId]/payment": { "orderId": string; }
  "/privacy": {}
  "/product-feed.xml": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/settings": {}
  "/shop/brands": {}
  "/shop/brands/[slug]": { "slug": string; }
  "/shop/categories": {}
  "/shop/categories/[slug]": { "slug": string; }
  "/shop/categories/connectivity": {}
  "/terms": {}
  "/track-order": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/products": never
  "/shop/brands": never
  "/shop/brands/[slug]": never
  "/shop/categories": never
  "/shop/categories/[slug]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
