// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shipping">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/licenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/licenses">> = Specific
  const handler = {} as typeof import("../../../src/app/licenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orders/[orderId]/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]/confirmation">> = Specific
  const handler = {} as typeof import("../../../src/app/orders/[orderId]/confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../src/app/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orders/[orderId]/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]/payment">> = Specific
  const handler = {} as typeof import("../../../src/app/orders/[orderId]/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/brands/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/brands/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/brands/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/categories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/categories/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/categories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/track-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track-order">> = Specific
  const handler = {} as typeof import("../../../src/app/track-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/emails/[emailId]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/[emailId]/retry">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/emails/[emailId]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/orders/[orderId]/email-invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[orderId]/email-invoice">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/orders/[orderId]/email-invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/payments/collect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments/collect">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/payments/collect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reconcile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/internal/email-outbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/email-outbox">> = Specific
  const handler = {} as typeof import("../../../src/app/api/internal/email-outbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/mpesa/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/mpesa/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/mpesa/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/mpesa/initiate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/mpesa/initiate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/mpesa/initiate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/status/[paymentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/status/[paymentId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/status/[paymentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/oauth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/oauth/google">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/oauth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/product-feed.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/product-feed.xml">> = Specific
  const handler = {} as typeof import("../../../src/app/product-feed.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../src/app/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/brands/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shop/brands/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/brands/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/brands/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shop/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/brands/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/categories/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shop/categories/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/categories/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/categories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shop/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/categories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
